In [4]:

import pdb
import os

import numpy as np
import pandas as pd

import json
import requests

import re

In [5]:
from common_definitions import (columns_restaurants,
                                types_restaurants,
                                columns_menu,
                                restaurant_columns_types)

In [6]:
# data collection paths
data_folder = './Data/'
# store some extra datra / intermediate results here:
folder_details = './Uber_eats_Details/'

In [ ]:
# req = 'https://www.ubereats.com/api/getFeedV1?localeCode=en-GB'

In [7]:
cookies = {
    'marketing_vistor_id': 'ef01aee6-0b60-486d-ab44-d349b5048c8d',
    'uev2.id.xp': '53628e61-8615-4d3c-9713-f381f8525caf',
    'dId': '8fc942c7-31a1-48a3-826b-b54a3e445361',
    'uev2.id.session': '2d980689-fdfe-4ddf-8d57-a4d8e489150b',
    'uev2.ts.session': '1575981221927',
    'jwt-session': 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1NzU5ODEyMjIsImV4cCI6MTU3NjA2NzYyMn0.OPZ7ooePMHMhKgu35PUEqyCIXJ2yeGeC9ilk8SV7U8A',
    'uev2.gdpr': 'true',
    'utag_main': 'v_id:016eefcdb58500116e279de9243c0004c002600900bd0$_sn:1$_se:15$_ss:0$_st:1575983949106$ses_id:1575981266310%3Bexp-session$_pn:3%3Bexp-session',
    '_userUuid': '',
    'AMCV_0FEC8C3E55DB4B027F000101%40AdobeOrg': '1611084164%7CMCMID%7C21714704783791517629078081350426887275',
    '_gcl_au': '1.1.1510728224.1575981267',
    'uev2.loc': '{%22address%22:{%22address1%22:%22Victoria%20Street%22%2C%22address2%22:%22Victoria%20St%2C%20Victoria%2C%20London%22%2C%22aptOrSuite%22:%22%22%2C%22city%22:%22%22%2C%22country%22:%22%22%2C%22eaterFormattedAddress%22:%22Victoria%20St%2C%20Victoria%2C%20London%2C%20UK%22%2C%22postalCode%22:%22%22%2C%22region%22:%22%22%2C%22subtitle%22:%22Victoria%20St%2C%20Victoria%2C%20London%22%2C%22title%22:%22Victoria%20Street%22%2C%22uuid%22:%22%22}%2C%22latitude%22:51.4966518%2C%22longitude%22:-0.1413492%2C%22reference%22:%22EiFWaWN0b3JpYSBTdCwgVmljdG9yaWEsIExvbmRvbiwgVUsiLiosChQKEgmvQa_D3gR2SBGJZZru8ozwwhIUChIJGwR8rCEFdkgRDuGUVcgktNc%22%2C%22referenceType%22:%22google_places%22%2C%22type%22:%22google_places%22}',
    'mcd_restaurant': 'Kati Roll',
}

headers = {
    'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0',
    'Accept': '*/*',
    'Accept-Language': 'en-US,en;q=0.5',
    'Content-Type': 'application/json',
    'x-csrf-token': 'x',
    'Origin': 'https://www.ubereats.com',
    'Connection': 'keep-alive',
    'Referer': 'https://www.ubereats.com/en-GB/feed/?pl=JTdCJTIyYWRkcmVzcyUyMiUzQSUyMlZpY3RvcmlhJTIwU3RyZWV0JTIyJTJDJTIycmVmZXJlbmNlJTIyJTNBJTIyRWlGV2FXTjBiM0pwWVNCVGRDd2dWbWxqZEc5eWFXRXNJRXh2Ym1SdmJpd2dWVXNpTGlvc0NoUUtFZ212UWFfRDNnUjJTQkdKWlpydThvend3aElVQ2hJSkd3UjhyQ0VGZGtnUkR1R1VWY2drdE5jJTIyJTJDJTIycmVmZXJlbmNlVHlwZSUyMiUzQSUyMmdvb2dsZV9wbGFjZXMlMjIlMkMlMjJsYXRpdHVkZSUyMiUzQTUxLjQ5NjY1MTglMkMlMjJsb25naXR1ZGUlMjIlM0EtMC4xNDEzNDkyJTdE',
    'TE': 'Trailers',
}

params = (
    ('localeCode', 'en-GB'),
)

data = '{"cacheKey":"JTdCJTIyYWRkcmVzcyUyMiUzQSUyMlZpY3RvcmlhJTIwU3RyZWV0JTIyJTJDJTIycmVmZXJlbmNlJTIyJTNBJTIyRWlGV2FXTjBiM0pwWVNCVGRDd2dWbWxqZEc5eWFXRXNJRXh2Ym1SdmJpd2dWVXNpTGlvc0NoUUtFZ212UWFfRDNnUjJTQkdKWlpydThvend3aElVQ2hJSkd3UjhyQ0VGZGtnUkR1R1VWY2drdE5jJTIyJTJDJTIycmVmZXJlbmNlVHlwZSUyMiUzQSUyMmdvb2dsZV9wbGFjZXMlMjIlMkMlMjJsYXRpdHVkZSUyMiUzQTUxLjQ5NjY1MTglMkMlMjJsb25naXR1ZGUlMjIlM0EtMC4xNDEzNDkyJTdE/DELIVERY////0/0////0/0/JTVCJTVE/","feedSessionCount":{"announcementCount":6,"announcementLabel":"\\"subscription.analytics_label\\""},"userQuery":"","chainName":"","date":"","startTime":0,"endTime":0,"carouselId":"","slugName":"","categorySlug":"","sortAndFilters":[]}'


#NB. Original query string below. It seems impossible to parse and
#reproduce query strings 100% accurately so the one below is given
#in case the reproduced version is not "correct".
# response = requests.post('https://www.ubereats.com/api/getFeedV1?localeCode=en-GB', headers=headers, cookies=cookies, data=data)

In [5]:
# get the response data

get_response = False

if get_response:
    response = requests.post('https://www.ubereats.com/api/getFeedV1', headers=headers, params=params, cookies=cookies, data=data)

In [6]:
# file name for the data dump
fn_victoria_street = 'response_victoria_street.json'

In [7]:
# save response content to file

save_response = False

if save_response is True:
    # save response as json file
    with open(fn_victoria_street, 'w') as jf:
        json.dump(json.loads(response.content), jf)
        jf.close()

In [8]:
# load response data from file
with open(fn_victoria_street, 'r') as jf:
    data_vs = json.load(jf)['data']

In [9]:
store_ids = list(data_vs['storesMap'].keys())

num_stores = len(store_ids)


# ['d7c942e8-d2b3-4004-b964-d8e008da75b0',
#  'bd0cb435-ba74-4d7d-9256-7071e0bcb29d',
#  'fa97c6bd-e139-4ffa-913a-263be6eaf2be',
#  ...
# ]

In [1]:
# data_vs.keys()

In [11]:
# for kk, elem in enumerate(data_vs['feedItems']):
#     print(kk)
#     print(elem['uuid'])

In [16]:
# data_vs['storesMap']

In [17]:
# data_vs['storesMap']['d7c942e8-d2b3-4004-b964-d8e008da75b0']

In [13]:
# set up empty data frame for storing restaurants
restaurants_df = pd.DataFrame(columns=columns_restaurants)  # , dtype=restaurant_columns_types)

In [2]:
# show the column labels
restaurants_df

NameError: name 'restaurants_df' is not defined

In [19]:
# mapper maps keys from our data structure to the given data,
# i.e., ours: theirs
mapper = {'name': 'title'}

In [40]:

# delivery_dur = []

# for sid in store_ids:  # [:10]:
#     store = data_vs['storesMap'][sid]
#     print(store['title'])

In [41]:
# data_vs['storesMap']

In [25]:
# data_vs['storesMap'][store_ids[2]]

In [20]:
# collect data from storesMap
data_arr = np.empty((num_stores, len(columns_restaurants)), dtype=object)

In [136]:

# keep, for merging in menu data
uuids = []

names = []
cuisines = []
description = []
price_cat = []
breakfast = []
lunch = []
sandwiches = []
city = []
post_code = []
street = []
number = []
number_addon = []
phone = []
url = []
lat = []
long = []
deliv_charge = []
min_order = []
pay_cash = []
wait_time = []
delivery_dur = []
deliv_postcode = []
rating = []
rating_count = []
data_src = []

In [137]:
names_store_ids = []


for sid in store_ids:
    store = data_vs['storesMap'][sid]
    
    uuids.append(store['uuid'])  # for identification
    
    title = store['title']
    title_only = title.split('(')[0]
    
    names_store_ids.append((title_only, store['uuid']))
    
    names.append(title_only)
    
    delivery = store['fareBadge']
    if delivery is not None:
        fare = re.findall("\d+\.\d+", delivery['text'])
        deliv_charge.append(float(fare[0]))
    else:
        deliv_charge.append(np.nan)

    price_cat.append(store['categories'][0] if not None else np.nan)

    cuisines.append(store['categories'][1:])
    try:
        rating.append(store['feedback']['rating'])
    except TypeError:
        rating.append(np.nan)
    try:
        rating_count.append(store['feedback']['ratingCount'])
    except TypeError:
        rating_count.append(np.nan)
    
    try:
        deliv_time_str = store['etaRange']['text']  # [:4]
        numbers_chars = [c for c in deliv_time_str if c.isnumeric()]
    
        if len(numbers_chars) == 2:
            # could be wrong for e.g. 5-7 minutes
            dur = float(''.join(numbers_chars))
        elif len(numbers_chars) == 3:
            dur = np.mean([float(''.join(numbers_chars[0])), float(''.join(numbers_chars[1:]))])
        elif len(numbers_chars) == 4:
            dur = np.mean([float(''.join(numbers_chars[:2])), float(''.join(numbers_chars[2:]))])
        else:
            dur = np.nan

        delivery_dur.append(dur)
    except TypeError:
        # print( store['etaRange'])  # this is typically None
        delivery_dur.append(np.nan)

In [138]:
len(names)

66

In [139]:
rest_df = pd.DataFrame(columns=columns_restaurants)

In [140]:
rest_df.loc[:, 'name'] = names
rest_df.loc[:, 'cuisine'] = cuisines

rest_df.loc[:, 'rating_value'] = rating
rest_df.loc[:, 'rating_count'] = rating_count

rest_df.loc[:, 'delivery_time'] = delivery_dur
rest_df.loc[:, 'delivery_charge'] = deliv_charge

rest_df.loc[:, 'price_category'] = price_cat

rest_df.loc[:, 'data_source'] = ['uber_eats'] * len(names)

rest_df.loc[:, 'uuid'] = uuids  # make sure to remove this again?

In [141]:
rest_df.head(2)
# rest_df.tail(2)

,name,cuisine,description,price_category,breakfast,lunch,sandwiches,city,post_code,street,...,min_order,payment_cash,payment_card,waiting_time,delivery_time,delivery_postcode,rating_value,rating_count,data_source,uuid
0,McDonald's®,"[Burger, Breakfast and brunch]",NaN,£,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,20.0,NaN,3.9,200+,uber_eats,d7c942e8-d2b3-4004-b964-d8e008da75b0
1,Starbucks,"[Coffee and tea, Breakfast and brunch, Cafe]",NaN,£,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,15.0,NaN,4.6,152,uber_eats,bd0cb435-ba74-4d7d-9256-7071e0bcb29d

In [142]:
# save the df as file into data storage folder
rest_df.to_json(os.path.join(data_folder, 'uber_eats.json'))

In [234]:
# load rest df
rest_df = pd.read_json(os.path.join(data_folder, 'uber_eats.json'))

In [143]:
# uuids for the stores
uuids = [x['uuid'] for x in data_vs['feedItems']]

In [144]:
# get menu data for a specific restaurant

headers = {
    'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0',
    'Accept': '*/*',
    'Accept-Language': 'en-US,en;q=0.5',
    'Content-Type': 'application/json',
    'x-csrf-token': 'x',
    'Origin': 'https://www.ubereats.com',
    'Connection': 'keep-alive',
    # 'Referer': 'https://www.ubereats.com/en-GB/london/food-delivery/pizza-hut-restaurants-piccadilly/MqgQGjGAQ12gbNyjr3p9Yw/',
    'TE': 'Trailers',
}

params = (
    ('localeCode', 'en-GB'),
)

# data = '{"storeUuid":"32a8101a-3180-435d-a06c-dca3af7a7d63", "sfNuggetCount":1}'

In [146]:
# collect menus for the restaurants, save to folder,
# one file per get_menu_responsesget_menu_responses = False

def strip_name(name_to_strip):
    """
    """
    return name_to_strip.strip().replace('\'', '').replace('-', '').replace(' ', '_').replace('/', '')


get_menu_responses = False

if get_menu_responses:
    menu_data = np.empty((len(names_store_ids), ), dtype=object)
    rest_w_menus_names = []

    for kk, name_store_id in enumerate(names_store_ids):
#         name = name_store_id[0].strip().replace('\'', '').replace('-', '').replace(' ', '_').replace('/', '')
        name = strip_name(name_store_id[0])
        store_id = name_store_id[1]

        # print(name)
        # print(store_id)
        rest_w_menus_names.append(name)

        # set up store uuid
        data = '{' + '"storeUuid":"{0}"'.format(store_id)  + ', "sfNuggetCount":1}'

        # get the data
        response_menu = requests.post('https://www.ubereats.com/api/getStoreV1', headers=headers, params=params, data=data)  # , cookies=cookies)

        try:
            resp_json = json.loads(response_menu.content)
            menu_data = resp_json['data']
        except ValueError:  # JSONDecodeError:
            print('Error, problem with response data')
            print(response_menu.content)
            continue  # skip this entry...

        # save menu items to a dedicated file
        with open(os.path.join(folder_details, name + '_' + store_id[:4] + '_details.json'), 'w') as jf:
            json.dump(menu_data, jf)
            jf.close()

In [10]:
# list of details files
detail_files = os.listdir(folder_details)

In [12]:
# get data from dumps of menu for restaurants

menu_data = {}
restaurant_locations = {}
restaurant_addresses = {}
restaurant_uuid = {}

for df in detail_files:
    print(df)  # print file name
    
    if not df.endswith('.json'):  # only use json file
        continue
        
    with open(os.path.join(folder_details, df), 'r') as jf:
        menu = json.load(jf)
        jf.close()

    try:
        loc_data = menu['location']  # dict with location data
        latitude = loc_data['latitude']
        longitude = loc_data['longitude']
        post_code = loc_data['postalCode']
        street_address = loc_data['streetAddress']
        city = loc_data['city']
        
        if street_address == post_code:
            street_address = ''
            
        leading_nr = re.findall('^\d+\s[A-z]+\s[A-z]+', street_address)
        leading_nr_2 = re.findall('^\d+\s[A-z]+', street_address)
        if leading_nr or leading_nr_2:
            number = street_address.split(' ')[0].strip()
            street_address = ' '.join(street_address.split(' ')[1:]).strip()
        else:
            number = None
        
        print('address: ', street_address)
        print('number: ', number)
        print('city: ', city)
        print(latitude, longitude)

    except KeyError:
        print('no location data')

    try:
        menues = menu['sectionEntitiesMap']
        keys = list(menues.keys())
        
        menu_items_list = []
       
        for key in keys:
            menu_items_keys = menues[key]
            
            for mi_key in menu_items_keys:  # iterate over the menu items
                # print(mi_key)
                menu_item = menues[key][mi_key]
                price_pounds =  str(menu_item['price'] / 100)
                name = menu_item['title']
                description = menu_item['description'] or ''
                
                menu_items_list.append([name, description, price_pounds])

            print('------> ' + 'no of menu items {}'.format(len(menu_items_list)))

        menu_data[df] = menu_items_list        
        restaurant_locations[df] = [longitude, latitude]
        restaurant_uuid[df] = menu['uuid']
        
        restaurant_addresses[df] = {'street': street_address,
                                    'post_code': post_code,
                                    'city': city,
                                    'number': number}
            
    except KeyError:
        print('no setctionEntitiesMap in data')
        print('\n')
        # continue

Ravello_Coffee_Co_b036_details.json
address:  Horseferry Rd
number:  41
city:
51.4946852 -0.1307491
------> no of menu items 62
------> no of menu items 120
Simit_Sarayi_871e_details.json
address:  Oxford St
number:  295
city:  London
51.514762 -0.144504
------> no of menu items 91
Mac_N_Cheese_a34b_details.json
address:  Pembridge Rd
number:  None
city:
51.50966839999999 -0.19711869999999998
------> no of menu items 71
Chelsea_Creperie_71c5_details.json
address:  Fulham Rd
number:  240
city:
51.485048 -0.1828949999999999
------> no of menu items 108
Portlands_247_692e_details.json
address:  Portlands 24/7
number:  None
city:  London
51.50224 -0.18883
------> no of menu items 45
------> no of menu items 73
Comptoir_Libanais_f2ac_details.json
address:  Exhibition Rd
number:  1
city:
51.494812084577916 -0.17356036412350762
------> no of menu items 19
------> no of menu items 91
Daily_Dose_Cold_Pressed_Juice_Bar_32f0_details.json
address:
number:  None
city:  London
51.508555 -0.143399
------> no of menu items 34
Giraffe_30c5_details.json
address:  Giraffe
number:  None
city:  London
51.493898 -0.142148
------> no of menu items 31
------> no of menu items 115
Duck_&_Waffle_Local_5956_details.json
address:  Haymarket
number:  52
city:  London
51.509288 -0.132998
------> no of menu items 31
------> no of menu items 62
------> no of menu items 107
Mapa_Cafe_bed5_details.json
no location data
no setctionEntitiesMap in data


Starbucks_bd0c_details.json
address:  Chantrey House
number:  None
city:
51.49442699999999 -0.1470627
------> no of menu items 150
Leon_5172_details.json
address:  Horseferry Rd
number:  None
city:  London
51.494636 -0.129328
------> no of menu items 74
------> no of menu items 173
McDonalds®_fdc3_details.json
address:  45/47 Whitehall
number:  None
city:  Westminster, London
51.506311 -0.126868
------> no of menu items 72
------> no of menu items 226
Frankie_&_Bennys_3cae_details.json
address:  Buckingham Palace Rd
number:  115
city:  London
51.494741 -0.145312
------> no of menu items 44
------> no of menu items 180
Lebaneats_Mayfair_9e20_details.json
address:  Lansdowne Row
number:  18
city:
51.5082058 -0.1445978
------> no of menu items 76
Pimlico_Shopper_aed8_details.json
address:
number:  None
city:  London
51.488857 -0.144257
------> no of menu items 139
Maroush_a8ce_details.json
address:  Maroush Bakehouse
number:  None
city:  London
51.493456 -0.194473
------> no of menu items 143
Caffe_Concerto_Cakes_6a67_details.json
address:  29-31 Piccadilly
number:  None
city:  London
51.509276 -0.136702
------> no of menu items 81
McColls__Westminster_395e_details.json
address:  Buckingham Gate
number:  None
city:
51.4987202 -0.1378915
------> no of menu items 114
ELAN_London__Belgravia_56be_details.json
address:  Lowndes St
number:  None
city:
51.498765 -0.15774349999999998
------> no of menu items 118
Krispy_Kreme_4b73_details.json
address:
number:  None
city:  London
51.494974 -0.144354
------> no of menu items 10
Denbigh_Food_and_Wine_978f_details.json
address:  Belgrave Rd
number:  33
city:
51.491176 -0.1394436
------> no of menu items 125
Richoux_95de_details.json
address:  Piccadilly, St. James's
number:  172
city:  London
51.50799 -0.139541
------> no of menu items 9
------> no of menu items 68
Pizza_Hot_afd3_details.json
address:  Battersea Park Rd
number:  42
city:
51.4757176 -0.1506025
------> no of menu items 118
------> no of menu items 237
Coco_Di_Mama_b770_details.json
no location data
no setctionEntitiesMap in data


Enough_to_Feed_an_Elephant_87b8_details.json
address:  York Rd
number:  63
city:  London
51.50250620000001 -0.1160336
------> no of menu items 65
Subway_895c_details.json
address:  MADDOX STREET
number:  10
city:  LONDON
51.5134959 -0.1417703
------> no of menu items 144
Balans_Soho_Society_18d5_details.json
address:  Kensington High St
number:  None
city:
51.500041806100654 -0.19545526247047193
------> no of menu items 69
Caffe_Concerto_Cakes_676e_details.json
address:  Kings Road
number:  52
city:  London
51.491615 -0.16013
------> no of menu items 81
Bagelicious_4e34_details.json
address:  Strutton Ground
number:  None
city:
51.497096476703845 -0.13374459264286773
------> no of menu items 90
Subway_177b_details.json
address:  2-4 UPPER ST MARTIN'S LANE UNIT 2
number:  None
city:  LONDON
51.5111141 -0.1273484
------> no of menu items 125
Tanyas_Deli_3c08_details.json
address:  Ixworth Pl, Chelsea
number:  35
city:  London
51.4919352 -0.1684544
------> no of menu items 39
ELAN_London__South_Kensington_0be9_details.json
address:  Brompton Rd
number:  None
city:  London
51.49665 -0.16859
------> no of menu items 121
McDonalds®_c792_details.json
address:  Eccleston Bridge
number:  None
city:
51.49374579999999 -0.14542629999999998
------> no of menu items 83
------> no of menu items 253
Cafe_Nuvo_c3cd_details.json
address:  Artillery Row
number:  12
city:
51.4964975 -0.1358261
------> no of menu items 78
.ipynb_checkpoints
Lahore_Grill_House_0e8d_details.json
address:  Edgware Rd
number:  117
city:  London
51.516487 -0.165523
------> no of menu items 23
Wonder_Chicken_ac12_details.json
address:  Victoria Place Shopping Centre
number:  None
city:
51.4946567 -0.1457209
------> no of menu items 31
McDonalds®_d7c9_details.json
address:  Victoria Street
number:  155
city:
51.496301445535515 -0.1403414898661733
------> no of menu items 83
------> no of menu items 253
Dominique_Ansel_Bakery_568d_details.json
address:  Elizabeth St
number:  17
city:
51.4928834 -0.1494293
------> no of menu items 64
Subway_cf92_details.json
address:  3-4 Sedley Pl
number:  None
city:
51.5143003 -0.1479365
------> no of menu items 144
Delizie_d’italia_30e7_details.json
address:  Lupus St
number:  70
city:
51.4879741 -0.1407063
------> no of menu items 61
------> no of menu items 96
Ecco_Pizzas_8c18_details.json
address:  Strutton Ground, Westminster
number:  40
city:  London
51.496599 -0.13389
------> no of menu items 27
Boki_Sevendials_7fc6_details.json
address:  Earlham St
number:  20
city:
51.5135553 -0.1276165
------> no of menu items 67
Premier_Food_and_Wine_f26f_details.json
address:  S Lambeth Rd
number:  139
city:
51.4785197 -0.12333849999999999
------> no of menu items 1006
The_Portman_2989_details.json
address:  Upper Berkeley St, Marylebone, London, UK
number:  51
city:  Maryleborne
51.515196 -0.161172
------> no of menu items 4
------> no of menu items 25
------> no of menu items 32
------> no of menu items 54
Crosstown_Doughnuts_bd86_details.json
no location data
no setctionEntitiesMap in data


Dupe_Coco_Di_Mama_13be_details.json
no location data
no setctionEntitiesMap in data


Patisserie_Valerie_b63e_details.json
address:  Wilton Road
number:  55
city:  London
51.493516 -0.141283
------> no of menu items 66
Subway_16b8_details.json
address:  COLLANADE WALK
number:  None
city:  VICTORIA, LONDON
51.493241 -0.1469751
------> no of menu items 144
Tiger_Cookies_0f93_details.json
address:  Shepherd St
number:  None
city:  London
51.506332 -0.146688
------> no of menu items 52
------> no of menu items 52
Kula_3849_details.json
address:  Marylebone
number:  None
city:  London
51.515112 -0.150872
------> no of menu items 109
------> no of menu items 235
VQ_f046_details.json
address:
number:  None
city:  London
51.486306 -0.17998
------> no of menu items 110
Spiers_df96_details.json
address:  Broadway
number:  55
city:  London
51.499412 -0.133781
------> no of menu items 4
------> no of menu items 6
------> no of menu items 8
------> no of menu items 13
------> no of menu items 17
Subway_bf22_details.json
address:  Embankment Pl
number:  19
city:
51.5072205 -0.12266809999999999
------> no of menu items 144
The_Pimlico_Shop_601d_details.json
address:  Sussex Food & Wine
number:  None
city:
51.488889 -0.144001
------> no of menu items 142
ELAN_London__Knightsbridge_681e_details.json
address:  Hans Cres
number:  None
city:
51.4997444 -0.1620681
------> no of menu items 111
Coco_Di_Mama_267e_details.json
no location data
no setctionEntitiesMap in data


Baker_&_Spice_e992_details.json
address:  54-56 Elizabeth Street
number:  None
city:  London
51.49409 -0.151263
------> no of menu items 150
La_Brioche_6281_details.json
address:  Old Brompton Rd
number:  40
city:
51.4934737 -0.17574599999999999
------> no of menu items 83
Simit_Sarayi_2a6e_details.json
address:  Villiers St
number:  33
city:  London
51.508074 -0.123571
------> no of menu items 91
Stack_&_Grill_d370_details.json
address:  Victoria Place Shopping Centre
number:  None
city:  London
51.494507 -0.145643
------> no of menu items 31
PAUL_fa97_details.json
address:
number:  None
city:  London
51.489597 -0.163846
------> no of menu items 89
Cardinals_Of_Mayfair_d08e_details.json
address:  115C Park St
number:  None
city:
51.51300229999999 -0.1560318
------> no of menu items 38
------> no of menu items 80
------> no of menu items 124
Yumchaa_820f_details.json
address:  Berwick St
number:  45
city:
51.5151937 -0.1360683
------> no of menu items 64
Mediterranean_Cafe_dd24_details.json
address:  Berwick St
number:  None
city:
51.51368840000001 -0.1347879
------> no of menu items 34
Subway_b146_details.json
address:  14A RATHBONE PLACE
number:  None
city:  LONDON
51.5172754 -0.1334765
------> no of menu items 143

In [13]:
res_uuid_df = pd.DataFrame.from_dict(restaurant_uuid, orient='index', columns=['uuid'])

In [14]:
res_loc_df = pd.DataFrame.from_dict(restaurant_locations, orient='index', columns=['longitude', 'latitude'])

In [15]:
res_address_df = pd.DataFrame.from_dict(restaurant_addresses, orient='index', columns=['street', 'post_code', 'city', 'number'])

In [16]:
# join the extra info
res_extra_df = res_uuid_df.join(res_address_df, how='inner').join(res_loc_df, how='inner')

In [17]:
res_extra_df.head(3)

,uuid,street,post_code,city,number,longitude,latitude
Ravello_Coffee_Co_b036_details.json,b03619f8-526e-4d18-8aca-90e98f2bc7d7,Horseferry Rd,SW1P 2AA,,41,-0.130749,51.494685
Simit_Sarayi_871e_details.json,871e6211-02ce-4319-87f9-ae27636d7056,Oxford St,W1C 2DY,London,295,-0.144504,51.514762
Mac_N_Cheese_a34b_details.json,a34ba690-0ddb-45f4-8395-c8feb8271fa8,Pembridge Rd,W11 3HL,,None,-0.197119,51.509668

In [18]:
for index, row in res_extra_df.iterrows():
    # try:
    rest_df.loc[rest_df['uuid'] == row['uuid'], 'post_code'] = row['post_code']
    rest_df.loc[rest_df['uuid'] == row['uuid'], 'longitude'] = row['longitude']
    rest_df.loc[rest_df['uuid'] == row['uuid'], 'latitude'] = row['latitude']
    rest_df.loc[rest_df['uuid'] == row['uuid'], 'street'] = row['street']
    rest_df.loc[rest_df['uuid'] == row['uuid'], 'number'] = row['number']
        

# rest_df.loc[rest_df['uuid'] == res_extra_df['uuid']]

NameError: name 'rest_df' is not defined

In [19]:
menu_list = []

for key in menu_data.keys():
    for elem in menu_data[key]:
        menu_list.append([key, *elem])

In [20]:
menu_data_df = pd.DataFrame(menu_list, columns=['fn', 'name', 'description', 'price']).set_index('fn')

In [21]:
menu_data_df = menu_data_df.join(res_uuid_df['uuid'])

In [22]:
menu_data_df.head(2)

,name,description,price,uuid
Bagelicious_4e34_details.json,Peanut Butter and Banana,,2.99,4e348f2e-5130-42d8-b302-7ed0012d5707
Bagelicious_4e34_details.json,"Egg, Bacon and Sausage",,5.99,4e348f2e-5130-42d8-b302-7ed0012d5707

In [338]:
restaurant_menu = pd.merge(rest_df, menu_data_df, how='left', left_on=['uuid'], right_on=['uuid'])

In [339]:
restaurant_menu.head(3)

,name_x,cuisine,description_x,price_category,breakfast,lunch,sandwiches,city,post_code,street,...,waiting_time,delivery_time,delivery_postcode,rating_value,rating_count,data_source,uuid,name_y,description_y,price
0,McDonald's®,"[Burger, Breakfast and brunch]",NaN,£,NaN,NaN,NaN,NaN,,Victoria Street,...,NaT,20.0,NaN,3.9,200+,uber_eats,d7c942e8-d2b3-4004-b964-d8e008da75b0,Bacon Roll with Tomato Ketchup,For nutritional and allergen information for o...,4.85
1,McDonald's®,"[Burger, Breakfast and brunch]",NaN,£,NaN,NaN,NaN,NaN,,Victoria Street,...,NaT,20.0,NaN,3.9,200+,uber_eats,d7c942e8-d2b3-4004-b964-d8e008da75b0,Vanilla Milkshake,For nutritional and allergen information for o...,2.99
2,McDonald's®,"[Burger, Breakfast and brunch]",NaN,£,NaN,NaN,NaN,NaN,,Victoria Street,...,NaT,20.0,NaN,3.9,200+,uber_eats,d7c942e8-d2b3-4004-b964-d8e008da75b0,Flake Raspberry Mini McFlurry®,For nutritional and allergen information for o...,1.69

In [17]:
# save the final data frame to file
restaurant_menu.to_json(os.path.join(data_folder, 'uber_eats_with_menu.json'))

NameError: name 'restaurant_menu' is not defined